### ISSUE TITLE
Parser doesn't trim whitespace from assignments

### ISSUE THREAD

**Issue by RyanGlScott** [nmattia/makefile#3]
With this simple `Makefile`:

```
CC = gcc
```

Parsing it with this library yields a somewhat surprising result:

```
λ> parseMakefile 
Right (Makefile {entries = [Assignment "CC " " gcc"]})
```

Notice that there are extra spaces around `CC` and `gcc`. This is pretty inconvenient, as it requires that I do a post-processing step on all parsed `Makefile`s to trim out the extra whitespace.

Wouldn't it make more sense to return `Right (Makefile {entries = [Assignment "CC" "gcc"]})` instead?

**Comment by nmattia** [comment]
I wondered about this one as I wrote it and thought it'd be better to have as close as possible to what the user wrote. After experimenting a bit with make today I believe you're right, both sides of the assignment should be stripped. Will fix asap.

**Comment by nmattia** [comment]
@RyanGlScott #7 should fix the issue. Feel free to close the ticket if this addresses your needs.

**Comment by RyanGlScott** [comment]
Thanks! I noticed that this doesn't trim all the whitespace from rules, however:

```makefile
foo :     gcc
```

```
λ> parseMakefile
Right (Makefile {entries = [Rule (Target "foo ") [Dependency "gcc"] []]})
```

**Comment by nmattia** [comment]
Alright, take 2. Let me know if that works.

**Comment by RyanGlScott** [comment]
It works! Thanks!
