### ISSUE TITLE
Parser is oblivious to escaped newlines

### ISSUE THREAD

**Issue by RyanGlScott** [nmattia/makefile#5]
[It is possible](https://www.gnu.org/software/make/manual/html_node/Splitting-Recipe-Lines.html) to split newlines in GNU Make, but the parser doesn't recognize this. With this `Makefile`:

```makefile
SUBDIRS=anna bspt cacheprof \
        compress compress2 fem
```

The parser yields this:

```
λ> parseMakefile 
Right (Makefile {entries = [Assignment "SUBDIRS" "anna bspt cacheprof \\"]})
```

I would expect:

```
Right (Makefile {entries = [Assignment "SUBDIRS" "anna bspt cacheprof compress compress2 fem"]})
```

**Comment by nmattia** [comment]
Good catch, thanks

**Comment by nmattia** [comment]
I've merged #12 , let me know if that deals with the problems you've seen.

**Comment by RyanGlScott** [comment]
Thanks, this is looking better. However, there are still some spots where the parser misses escaped newlines. For example, in rules:

```makefile
foo: anna bspt cacheprof \
        compress compress2 fem
```
```
λ> parseMakefile
Right (Makefile {entries = [Rule (Target "foo") [Dependency "anna",Dependency "bspt",Dependency "cacheprof",Dependency "\\"] [Command "compress compress2 fem"]]})
```

And in commands themselves:

```makefile
foo:
        cd dir/ && \
        ls
```
```
λ> parseMakefile
Right (Makefile {entries = [Rule (Target "foo") [] [Command "cd dir/ && \\",Command "ls"]]})
```

**Comment by nmattia** [comment]
Heh, I took a somewhat lazy approach there. 9758bddeb5bf6a8a422e7f51a2ff24742b764e63 should deal with commands and dependencies. It doesn't support comments after the `\`, but neither does `make` AFAICT.

**Comment by RyanGlScott** [comment]
Great, thanks!
